server:
    port: 9000
logging:
    level:
        root: ERROR
        org.springframework.web: INFO
        com.hobby.springbootvue: DEBUG
        org.hibernate: INFO
        io.undertow.server: DEBUG
        io.undertow.websockets: DEBUG