server:
    port: 9000
logging:
    level:
        root: ERROR
        org.springframework.web: INFO
        com.hobby.springbootvue: DEBUG
        org.hibernate: INFO
        io.undertow.server: DEBUG
        io.undertow.websockets: DEBUG
spring:
    datasource:
        url: jdbc:h2:file:./data/h2;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create