server:
    port: 9000
logging:
    level:
        root: INFO
        org.springframework.web: INFO
        com.hobby.springbootvue: DEBUG
        reactor.netty.http.client.HttpClient: DEBUG
spring:
    r2dbc:
        url: r2dbc:h2:file:///./data/h2;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;
        username: sa
        password: